### ISSUE TITLE
Make file on windows failing to run make build-doc

### ISSUE THREAD

**Issue by Nova38** [wenkokke/talondoc#21]
The current make file is failing to run make build-doc for me on my windows 11 machine. I have gnu make 4.3 installed from scoop. The issue seems to be the Lines that start with @# ( https://github.com/wenkokke/talondoc/blob/b4388a96f92897975dcffb184260ce9c494507f7/Makefile#L5-L8). When i remove the comments the make file is able to run correctly.
```bash
make build-doc
poetry install -E docs
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: talondoc (0.1.1)
# @# NOTE: Always clean the environment, because 'analyze_package' does
process_begin: CreateProcess(NULL, # @# NOTE: Always clean the environment, because analyze_package does, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:6: build-doc] Error 2
```

**Comment by wenkokke** [comment]
Ah, sorry! Fixed in HEAD, simple because I happened to remove the comments. But, yeah, that syntax was shell specific.
