### ISSUE TITLE
Add devcontainer

### ISSUE THREAD

**Issue by Nova38** [wenkokke/talondoc#37]
Devcontainer's allow for a consistent development environment isolated from the base system. They are useful for helping to isolate bugs that could be due to a misconfiguration on a developer's device from bugs that arise from the core project. I will make a pull request for this issue where I will have it setup the poetry environment.

**Comment by Nova38** [comment]
The  devcontainer currently only has python3.10 installed. It doesn't look like there is an inbuilt feature for installing multiple system pythons in the devcontainer features. Should we use pyenv to install 3.9 and 3.11 for the tests?

**Comment by wenkokke** [comment]
Yes, and 3.9 should probably be the default.

**Comment by wenkokke** [comment]
Fixed by #131
