### ISSUE TITLE
Include descriptions for builtin objects

### ISSUE THREAD

**Issue by wenkokke** [wenkokke/talondoc#4]
Talon has a number of builtin objects, mostly actions, which come with their own documentation. Since talondoc runs outside of Talon, it doesn't have access to this documentation, so `TalonScriptDescriber.describe` fails when it encounters a builtin action, see [talondoc/util/describer.py#L104-L126][describe].

We should write a script which extracts this information to a versioned `.json` file, and add the contents of this file to the registry when talondoc loads.

An easy way to access this information is to capture the output of running `actions.list()` in ` ~/.talon/bin/repl`.

[describe]: https://github.com/wenkokke/talondoc/blob/d1d68b3844cacb825484fb6a8740c33b44ed3da4/talondoc/util/describer.py#L104-L126

**Comment by Nova38** [comment]
I think this would be a good first issue for me to tackle

**Comment by wenkokke** [comment]
Would probably be good to just write a function that extracts the information from Talon and saves it as a YAML or JSON file. We can hook it into talondoc via #5.

**Comment by wenkokke** [comment]
Ideally, construct instances of the `ActionEntry`, `TagEntry`, `CaptureEntry`, *etc*, classes in `talondoc.analyse.entries`, and use the dataclasses `to_dict` and `from_dict` functions with dumps and loads from the `json` module to write and read the file.
